const actions = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',

  // POST
  SET_POST_LIST: 'SET_POST_LIST',
  SET_POST_DETAIL: 'SET_POST_DETAIL',
  SET_POST_COMMENTS: 'SET_POST_COMMENTS',

  // USER
  SET_USER_LIST: 'SET_USER_LIST',
  SET_USER_DETAIL: 'SET_USER_DETAIL',
  SET_USER_POSTS: 'SET_USER_POSTS',
  SET_USER_ALBUMS: 'SET_USER_ALBUMS',

  // ALBUMS
  SET_ALBUMS_LIST: 'SET_ALBUMS_LIST',
  SET_ALBUMS_INFO: 'SET_ALBUMS_INFO',
  SET_ALBUMS_PHOTOS: 'SET_ALBUMS_PHOTOS',
};

export default actions;
