const actions = {
  SET_LOADING: 'SET_LOADING',
  SET_FAILED: 'SET_FAILED',

  // POST
  SET_POST_LIST: 'SET_POST_LIST',
  SET_POST_DETAIL: 'SET_POST_DETAIL',
  SET_POST_COMMENTS: 'SET_POST_COMMENTS',
};

export default actions;
